ARG BASE_IMAGE
FROM ${BASE_IMAGE}

COPY --chown=miru:miru server/miru_server/api/rest.py /app/miru_server/api/rest.py
COPY --chown=miru:miru server/miru_server/api/ws.py /app/miru_server/api/ws.py
COPY --chown=miru:miru server/miru_server/core/events.py /app/miru_server/core/events.py
